apiVersion: v1
kind: Service
metadata:
  name: hello-svc
spec:
  selector:
    app: hello
  type: NodePort
  ports:
    - port: 8200
      targetPort: 8000
      nodePort: 30000
  #externalIPs:
  #  - 192.168.65.3
